# INSTRUÇÃO PRÁTICA - IP-P007
## Revisam e consolidaçao do conteúdo de __Pandas__ avançado.

### __Exercício 1: Carregando e analisando um DataSet__

Dados de estações metereologicas por ano: [Instituto Nacional de Meteorologia](https://portal.inmet.gov.br/dadoshistoricos). 
1. Download de dados de 2003, 2013 e 2023 da estação Salvador.
2. Carregando e analizando dados das três estações em ``DataFrame``s separados.

In [68]:
import pandas as pd

# carregando os aquivos csv
estacao_ssa_2003 = pd.read_csv('../datasets/estacao_Salvador_2003.csv', sep=";", header=8, encoding='latin-1')
estacao_ssa_2013 = pd.read_csv('../datasets/estacao_Salvador_2013.csv', sep=",", header=8, encoding='utf-8')
estacao_ssa_2023 = pd.read_csv('../datasets/estacao_Salvador_2023.csv', sep=";", header=8, encoding='latin-1')

In [69]:
# estacao em 2003
estacao_ssa_2003.info()
estacao_ssa_2003.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 20 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   DATA (YYYY-MM-DD)                                      8760 non-null   object
 1   HORA (UTC)                                             8760 non-null   object
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       8760 non-null   object
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  8760 non-null   object
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        8760 non-null   object
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       8760 non-null   object
 6   RADIACAO GLOBAL (KJ/m²)                                8760 non-null   int64
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           8760 non-null   object
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   8760 non-null   object
 9   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             8760 non-null   object
 10  TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)             8760 non-null   object
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       8760 non-null   object
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       8760 non-null   object
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               8760 non-null   int64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               8760 non-null   int64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    8760 non-null   int64
 16  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   8760 non-null   int64
 17  VENTO, RAJADA MAXIMA (m/s)                             8760 non-null   object
 18  VENTO, VELOCIDADE HORARIA (m/s)                        8760 non-null   object
 19  Unnamed: 19                                            0 non-null      float64
dtypes: float64(1), int64(5), object(14)
memory usage: 1.3+ MB

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2003-01-01,00:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN
1,2003-01-01,01:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN
2,2003-01-01,02:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN
3,2003-01-01,03:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN
4,2003-01-01,04:00,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,NaN

In [70]:
# estacao em 2013
estacao_ssa_2013.info()
estacao_ssa_2013.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 19 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   DATA (YYYY-MM-DD)                                      8760 non-null   object
 1   HORA (UTC)                                             8760 non-null   object
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       8760 non-null   object
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  8760 non-null   object
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        8760 non-null   object
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       8760 non-null   object
 6   RADIACAO GLOBAL (KJ/m²)                                8760 non-null   object
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           8760 non-null   object
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   8760 non-null   object
 9   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             8760 non-null   object
 10  TEMPERATURA M�NIMA NA HORA ANT. (AUT) (�C)             8760 non-null   object
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       8760 non-null   object
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       8760 non-null   object
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               8760 non-null   int64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               8760 non-null   int64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    8760 non-null   int64
 16  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   8760 non-null   int64
 17  VENTO, RAJADA MAXIMA (m/s)                             8760 non-null   object
 18  VENTO, VELOCIDADE HORARIA (m/s)                        8760 non-null   object
dtypes: int64(4), object(15)
memory usage: 1.3+ MB

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA M�NIMA NA HORA ANT. (AUT) (�C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2013-01-01,00:00,0,"1008,3","1008,3",1008,-9999,"25,7",22,"25,8","25,5","22,1","21,6",80,78,80,97,"5,1","1,5"
1,2013-01-01,01:00,0,"1008,5","1008,5","1008,2",-9999,"25,8","21,9","25,9","25,4","22,1","21,6",80,79,79,96,"5,4","1,8"
2,2013-01-01,02:00,0,"1008,4","1008,5","1008,4",-9999,"25,3","21,9","25,8","25,1","21,9",21,81,78,81,103,"4,5","1,3"
3,2013-01-01,03:00,0,1008,"1008,4",1008,-9999,"25,3","21,5","25,5","25,2","21,9","21,4",81,79,80,85,"5,1","1,3"
4,2013-01-01,04:00,0,"1007,3",1008,"1007,3",-9999,"25,1","21,4","25,5","25,1","21,6","21,4",80,79,80,62,"5,5","1,1"

In [71]:
# estacao em 2023
estacao_ssa_2023.info()
estacao_ssa_2023.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 20 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Data                                                   8760 non-null   object
 1   Hora UTC                                               8760 non-null   object
 2   PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                       8756 non-null   object
 3   PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  8756 non-null   object
 4   PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)        8756 non-null   object
 5   PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)       8756 non-null   object
 6   RADIACAO GLOBAL (Kj/m²)                                4735 non-null   object
 7   TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)           8756 non-null   object
 8   TEMPERATURA DO PONTO DE ORVALHO (°C)                   8756 non-null   object
 9   TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)             8756 non-null   object
 10  TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)             8756 non-null   object
 11  TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)       8756 non-null   object
 12  TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)       8756 non-null   object
 13  UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)               8756 non-null   float64
 14  UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)               8756 non-null   float64
 15  UMIDADE RELATIVA DO AR, HORARIA (%)                    8756 non-null   float64
 16  VENTO, DIREÇÃO HORARIA (gr) (° (gr))                   8756 non-null   float64
 17  VENTO, RAJADA MAXIMA (m/s)                             8756 non-null   object
 18  VENTO, VELOCIDADE HORARIA (m/s)                        8756 non-null   object
 19  Unnamed: 19                                            0 non-null      float64
dtypes: float64(5), object(15)
memory usage: 1.3+ MB

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0,"1009,2","1009,2","1008,8",NaN,"26,2","21,8","26,3","26,1",22,"21,7",78.0,77.0,77.0,77.0,"4,7","1,3",NaN
1,2023/01/01,0100 UTC,0,"1009,4","1009,4","1009,2",NaN,"26,1",22,"26,3",26,22,"21,8",78.0,76.0,78.0,90.0,"4,7",1,NaN
2,2023/01/01,0200 UTC,0,"1009,1","1009,4","1009,1",NaN,26,22,"26,3",26,"22,3",22,79.0,78.0,79.0,79.0,5,",9",NaN
3,2023/01/01,0300 UTC,0,"1008,5","1009,1","1008,5",NaN,"25,8","21,9",26,"25,6","22,1","21,8",80.0,79.0,79.0,84.0,"4,8",1,NaN
4,2023/01/01,0400 UTC,"3,4","1008,1","1008,5","1008,1",NaN,"23,7","21,7","25,8","23,7","22,1","21,6",89.0,79.0,89.0,52.0,"4,6","1,4",NaN

### __Exercício 2: Juntando os datasets__

1. Constrindo um novo ``DataFrame`` utilizando um ``MultiIndex``.

In [72]:
# convertendo a coluna data para o tipo datetime
estacao_ssa_2003['DATA (YYYY-MM-DD)'] = pd.to_datetime(estacao_ssa_2003['DATA (YYYY-MM-DD)'])
estacao_ssa_2013['DATA (YYYY-MM-DD)'] = pd.to_datetime(estacao_ssa_2013['DATA (YYYY-MM-DD)'])
estacao_ssa_2023['Data'] = pd.to_datetime(estacao_ssa_2023['Data'])


# pegando listas com os anos, meses e dias de cada dataframe
anos = pd.concat([estacao_ssa_2003['DATA (YYYY-MM-DD)'].dt.year,
                  estacao_ssa_2013['DATA (YYYY-MM-DD)'].dt.year,
                  estacao_ssa_2023['Data'].dt.year])
anos = anos.values

meses = pd.concat([estacao_ssa_2003['DATA (YYYY-MM-DD)'].dt.month,
                   estacao_ssa_2013['DATA (YYYY-MM-DD)'].dt.month,
                   estacao_ssa_2023['Data'].dt.month])
meses = meses.values

dias = pd.concat([estacao_ssa_2003['DATA (YYYY-MM-DD)'].dt.day,
                  estacao_ssa_2013['DATA (YYYY-MM-DD)'].dt.day,
                  estacao_ssa_2023['Data'].dt.day])


# criando indice
index = pd.MultiIndex.from_arrays([anos, meses, dias], names=['ano', 'mes', 'dia'])

In [73]:
# removendo colunas extraas
estacao_ssa_2003.drop(columns=['Unnamed: 19'], inplace=True)
estacao_ssa_2023.drop(columns=['Unnamed: 19'], inplace=True)

In [74]:
# unificando os dataframes
print("Colunas antes:")
colunas_2003 = estacao_ssa_2003.columns.values.tolist()
colunas_2013 = estacao_ssa_2013.columns.values.tolist()
colunas_2023 = estacao_ssa_2023.columns.values.tolist()

print(colunas_2003)
print(colunas_2013)
print(colunas_2023)

# renomeando colunas diferentes
print("\nColunas diferentes:")
for c_2003, c_2013, c_2023 in zip(colunas_2003, colunas_2013, colunas_2023):
    if c_2003 != c_2013 or c_2003 != c_2023:
        print(f"'{c_2003}' | '{c_2013}' | '{c_2023}'")
        estacao_ssa_2013.rename(columns={c_2013: c_2003}, inplace=True)
        estacao_ssa_2023.rename(columns={c_2023: c_2003}, inplace=True)


# imprimindo colunas depois
print("\nColunas depois:")
colunas_2003 = estacao_ssa_2003.columns.values.tolist()
colunas_2013 = estacao_ssa_2013.columns.values.tolist()
colunas_2023 = estacao_ssa_2023.columns.values.tolist()

print(colunas_2003)
print(colunas_2013)
print(colunas_2023)

Colunas antes:
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA M�NIMA NA HORA ANT. (AUT) (�C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']
['Data', 'Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (Kj/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']

Colunas diferentes:
'DATA (YYYY-MM-DD)' | 'DATA (YYYY-MM-DD)' | 'Data'
'HORA (UTC)' | 'HORA (UTC)' | 'Hora UTC'
'RADIACAO GLOBAL (KJ/m²)' | 'RADIACAO GLOBAL (KJ/m²)' | 'RADIACAO GLOBAL (Kj/m²)'
'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)' | 'TEMPERATURA M�NIMA NA HORA ANT. (AUT) (�C)' | 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)'

Colunas depois:
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']
['DATA (YYYY-MM-DD)', 'HORA (UTC)', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)', 'RADIACAO GLOBAL (KJ/m²)', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)', 'TEMPERATURA DO PONTO DE ORVALHO (°C)', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)', 'UMIDADE RELATIVA DO AR, HORARIA (%)', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))', 'VENTO, RAJADA MAXIMA (m/s)', 'VENTO, VELOCIDADE HORARIA (m/s)']

In [75]:
# criando dataframa multiindexado por ano, mes e dia
estacao_ssa = pd.concat([estacao_ssa_2003, estacao_ssa_2013, estacao_ssa_2023]).drop(columns=['DATA (YYYY-MM-DD)', 'HORA (UTC)'])
estacao_ssa.set_index(index, inplace=True)
estacao_ssa

             PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
ano  mes dia
2003 1   1                              -9999  \
         1                              -9999
         1                              -9999
         1                              -9999
         1                              -9999
...                                       ...
2023 12  31                                 0
         31                                 0
         31                                 0
         31                                 0
         31                                 0

             PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ano  mes dia
2003 1   1                                                -9999     \
         1                                                -9999
         1                                                -9999
         1                                                -9999
         1                                                -9999
...                                                         ...
2023 12  31                                              1004,6
         31                                              1004,8
         31                                                1005
         31                                              1005,3
         31                                              1005,8

             PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                             -9999  \
         1                                             -9999
         1                                             -9999
         1                                             -9999
         1                                             -9999
...                                                      ...
2023 12  31                                           1005,1
         31                                           1004,8
         31                                           1005,1
         31                                           1005,3
         31                                           1005,8

             PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                              -9999  \
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                            1004,6
         31                                            1004,5
         31                                            1004,8
         31                                            1004,9
         31                                            1005,3

             RADIACAO GLOBAL (KJ/m²)
ano  mes dia
2003 1   1                     -9999  \
         1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
...                              ...
2023 12  31                   1641,3
         31                    644,8
         31                    148,7
         31                      NaN
         31                      NaN

             TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ano  mes dia
2003 1   1                                          -9999  \
         1                                          -9999
         1                                          -9999
         1                                          -9999
         1                                          -9999
...                                                   ...
2023 12  31                                          29,9
         31                                          28,4
         31                                          27,3
         31                                            27
         31                                          26,7

             TEMPERATURA DO PONTO DE ORVALHO (°C)
ano  mes dia
2003 1   1                                  -9999  \
         1                                  -9999
         1                                  -9999
         1                                  -9999
         1                                  -9999
...                                           ...
2023 12  31                                  21,9
         31                                  21,9
         31                                  22,3
         31                                  22,3
         31                                  22,7

             TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                        -9999  \
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
...                                                 ...
2023 12  31                                        30,9
         31                                        29,9
         31                                        28,4
         31                                        27,3
         31                                        27,1

             TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                        -9999  \
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
...                                                 ...
2023 12  31                                        29,7
         31                                        28,4
         31                                        27,3
         31                                          27
         31                                        26,7

             TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                              -9999  \
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                              23,1
         31                                              22,6
         31                                              22,4
         31                                              22,3
         31                                              22,7

             TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                              -9999  \
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                              21,6
         31                                              21,8
         31                                              21,8
         31                                              22,1
         31                                              22,3

              UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                     -9999.0  \
         1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
...                                                ...
2023 12  31                                       64.0
         31                                       69.0
         31                                       74.0
         31                                       75.0
         31                                       79.0

              UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                     -9999.0  \
         1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
         1                                     -9999.0
...                                                ...
2023 12  31                                       61.0
         31                                       62.0
         31                                       68.0
         31                                       73.0
         31                                       75.0

              UMIDADE RELATIVA DO AR, HORARIA (%)
ano  mes dia
2003 1   1                                -9999.0  \
         1                                -9999.0
         1                                -9999.0
         1                                -9999.0
         1                                -9999.0
...                                           ...
2023 12  31                                  62.0
         31                                  68.0
         31                                  74.0
         31                                  75.0
         31                                  78.0

              VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)
ano  mes dia
2003 1   1                                 -9999.0                      -9999  \
         1                                 -9999.0                      -9999
         1                                 -9999.0                      -9999
         1                                 -9999.0                      -9999
         1                                 -9999.0                      -9999
...                                            ...                        ...
2023 12  31                                  106.0                        6,4
         31                                   91.0                        5,7
         31                                   80.0                        4,9
         31                                   65.0                        4,3
         31                                   74.0                        5,2

             VENTO, VELOCIDADE HORARIA (m/s)
ano  mes dia
2003 1   1                             -9999
         1                             -9999
         1                             -9999
         1                             -9999
         1                             -9999
...                                      ...
2023 12  31                              1,2
         31                              1,6
         31                              1,3
         31                                1
         31                              1,4

[26280 rows x 17 columns]

2. Construindo novo ``DataFrame`` utilizando ``MultiIndex`` como colunas contendo os parâmetros agrupados (precipitações, pressão, radiação, temperatura, umidade, velocidade do vento)

In [76]:
# criando multiindex para as colunas
nivel_1 = ['precipitacao'] + ['pressao']*3 + ['radiacao'] + ['temperatura']*6 + ['umidade']*3 + ['velocidade do vento']*3
nivel_2 = colunas_2003[2:]

# definindo multiindex para as colunas
index_col = pd.MultiIndex.from_arrays([nivel_1, nivel_2], names=['medicao', 'tipo'])

estacao_ssa.columns = index_col
estacao_ssa

medicao                          precipitacao
tipo         PRECIPITAÇÃO TOTAL, HORÁRIO (mm)
ano  mes dia
2003 1   1                              -9999  \
         1                              -9999
         1                              -9999
         1                              -9999
         1                              -9999
...                                       ...
2023 12  31                                 0
         31                                 0
         31                                 0
         31                                 0
         31                                 0

medicao                                                    pressao
tipo         PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ano  mes dia
2003 1   1                                                -9999     \
         1                                                -9999
         1                                                -9999
         1                                                -9999
         1                                                -9999
...                                                         ...
2023 12  31                                              1004,6
         31                                              1004,8
         31                                                1005
         31                                              1005,3
         31                                              1005,8

medicao
tipo         PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                             -9999  \
         1                                             -9999
         1                                             -9999
         1                                             -9999
         1                                             -9999
...                                                      ...
2023 12  31                                           1005,1
         31                                           1004,8
         31                                           1005,1
         31                                           1005,3
         31                                           1005,8

medicao
tipo         PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ano  mes dia
2003 1   1                                              -9999  \
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                            1004,6
         31                                            1004,5
         31                                            1004,8
         31                                            1004,9
         31                                            1005,3

medicao                     radiacao
tipo         RADIACAO GLOBAL (KJ/m²)
ano  mes dia
2003 1   1                     -9999  \
         1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
...                              ...
2023 12  31                   1641,3
         31                    644,8
         31                    148,7
         31                      NaN
         31                      NaN

medicao                                       temperatura
tipo         TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ano  mes dia
2003 1   1                                          -9999  \
         1                                          -9999
         1                                          -9999
         1                                          -9999
         1                                          -9999
...                                                   ...
2023 12  31                                          29,9
         31                                          28,4
         31                                          27,3
         31                                            27
         31                                          26,7

medicao
tipo         TEMPERATURA DO PONTO DE ORVALHO (°C)
ano  mes dia
2003 1   1                                  -9999  \
         1                                  -9999
         1                                  -9999
         1                                  -9999
         1                                  -9999
...                                           ...
2023 12  31                                  21,9
         31                                  21,9
         31                                  22,3
         31                                  22,3
         31                                  22,7

medicao
tipo         TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                        -9999  \
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
...                                                 ...
2023 12  31                                        30,9
         31                                        29,9
         31                                        28,4
         31                                        27,3
         31                                        27,1

medicao
tipo         TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                        -9999  \
         1                                        -9999
         1                                        -9999
         1                                        -9999
         1                                        -9999
...                                                 ...
2023 12  31                                        29,7
         31                                        28,4
         31                                        27,3
         31                                          27
         31                                        26,7

medicao
tipo         TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                              -9999  \
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                              23,1
         31                                              22,6
         31                                              22,4
         31                                              22,3
         31                                              22,7

medicao
tipo         TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ano  mes dia
2003 1   1                                              -9999  \
         1                                              -9999
         1                                              -9999
         1                                              -9999
         1                                              -9999
...                                                       ...
2023 12  31                                              21,6
         31                                              21,8
         31                                              21,8
         31                                              22,1
         31                                              22,3

medicao                                       umidade
tipo         UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                    -9999.0  \
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
...                                               ...
2023 12  31                                      64.0
         31                                      69.0
         31                                      74.0
         31                                      75.0
         31                                      79.0

medicao
tipo         UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ano  mes dia
2003 1   1                                    -9999.0  \
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
         1                                    -9999.0
...                                               ...
2023 12  31                                      61.0
         31                                      62.0
         31                                      68.0
         31                                      73.0
         31                                      75.0

medicao
tipo         UMIDADE RELATIVA DO AR, HORARIA (%)
ano  mes dia
2003 1   1                               -9999.0  \
         1                               -9999.0
         1                               -9999.0
         1                               -9999.0
         1                               -9999.0
...                                          ...
2023 12  31                                 62.0
         31                                 68.0
         31                                 74.0
         31                                 75.0
         31                                 78.0

medicao                       velocidade do vento
tipo         VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)
ano  mes dia
2003 1   1                                -9999.0                      -9999  \
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999
         1                                -9999.0                      -9999
...                                           ...                        ...
2023 12  31                                 106.0                        6,4
         31                                  91.0                        5,7
         31                                  80.0                        4,9
         31                                  65.0                        4,3
         31                                  74.0                        5,2

medicao
tipo         VENTO, VELOCIDADE HORARIA (m/s)
ano  mes dia
2003 1   1                             -9999
         1                             -9999
         1                             -9999
         1                             -9999
         1                             -9999
...                                      ...
2023 12  31                              1,2
         31                              1,6
         31                              1,3
         31                                1
         31                              1,4

[26280 rows x 17 columns]

### __Exercício 3: Analisando os DataFrame__

1. Analisando as colunas relacionadas a precipitações e temperaturas.

2. Comparando dados para o mes de Janeiro.

3. Comparando as informações sobre temperatura e precipitações medias em cada uma das estações dos três anos.

4. Comparando informações sobre temperatura e precipitações medias para o dia 28 de setembro  em cada um dos intervalos do dia dos três anos.